### ISSUE TITLE
Some Enum-type objects don't list available options

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#593] opened 2023-10-18 12:39 UTC
### Feature description

e.g. docker.pullPolicy

![image](https://github.com/kestra-io/docs/assets/86264395/0402752e-fd4b-4f34-a08e-c2f4ff22f489)

**Comment by yuri1969** [comment] 2023-10-23 06:32
This seems to be a duplicate of https://github.com/kestra-io/kestra/issues/2319

**Closed** 2023-10-27 11:04 UTC
Labels: enhancement
